# Generated by Django 2.0.5 on 2018-06-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affective', models.CharField(choices=[('Boring', 'Boring'), ('Confusing', 'Confusing'), ('Engaging', 'Engaging')], default='Boring', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cognitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognitive', models.CharField(choices=[('Difficult', 'Difficult'), ('Easy', 'Easy')], default='Difficult', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cognitive',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cognitives', to='feedback.Url'),
        ),
        migrations.AddField(
            model_name='affective',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectives', to='feedback.Url'),
        ),
    ]
