# Generated by Django 2.0.5 on 2018-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180612_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='pub_name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
